### ISSUE TITLE
Photos Crashes during Importing OS8

### ISSUE THREAD

**Issue by WindHillWebs** [elementary/photos#787]
### What Happened?

During Auto-Import on OS8, Photos closes. 

### Steps to Reproduce

Opened Photos and all the events seemed to be there but it then tried to Auto-Import with a status bar showing 0%. It then crashes.

### Expected Behavior

Expected Photos to fully import all images and remain open for use.

### OS Version

8.x (Circe)

### Session Type

Classic Session (X11, This is the default)

### Software Version

Latest release (I have run all updates)

### Hardware Info

MacBook Pro 7,1

**Comment by jeremypw** [comment]
Thanks for the report. Are you running a version compiled from the latest source-code or the stable release? There was a fix recently pushed for one cause of crashing on importing certain photos but there may be a different cause in your case of course.  If you are able to run Photos under `gdb` in a terminal and then get a backtrace (by entering `bt`) it would help to identify the cause.  Please also confirm the type(s) of image/video formats you are importing so we can try to reproduce.

**Comment by jeremypw** [comment]
Hmm, just checked on OS8 in a VM and the Photos installed from the AppCenter is a Flatpak from the stable branch so you will not have got that fix yet, I guess.

**Comment by dominichayesferen** [comment]
Possibly related crash output from the Flatpak over here:
https://pastebin.com/hiLd6uc8

NOTE: some filenames were censored as `[censored]` in the output

**Comment by jeremypw** [comment]
You may be able to get more information by running the flatpak in debug mode and using `gdb`:

```
flatpak run --command=sh --devel io.elementary.photos
```

At the new shell commandline:
```
gdb io.elementary.photos
run
```

After a crash enter `bt` to get a backtrace.

Further improved info is provided by installing the separate DEBUG flatpak for the runtime
$ flatpak install io.elementary.Sdk.Debug  (choose version matching app to debug's manifest)
NOTE: The debug package is large (3.9GB) and may be slow to download.

**Comment by dominichayesferen** [comment]
```
** (io.elementary.photos:13): WARNING **: 09:21:21.274: Failed to decode XMP metadata.

Thread 53 "pool-io.element" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff3effd6c0 (LWP 114)]
0x00007ffff6684295 in __vfscanf_internal (s=s@entry=0x7fff3effc6c0, 
    format=format@entry=0x5555557c91d6 "%4d%2d%2d%2d%2d%2d", 
    argptr=argptr@entry=0x7fff3effc6a8, mode_flags=mode_flags@entry=2)
    at vfscanf-internal.c:1928
1928                        *ARG (unsigned int *) = (unsigned int) num.ul;
(gdb) bt
#0  0x00007ffff6684295 in __vfscanf_internal
    (s=s@entry=0x7fff3effc6c0, format=format@entry=0x5555557c91d6 "%4d%2d%2d%2d%2d%2d", argptr=argptr@entry=0x7fff3effc6a8, mode_flags=mode_flags@entry=2)
    at vfscanf-internal.c:1928
#1  0x00007ffff667478c in __GI___isoc99_sscanf
    (s=0x7fff24003b00 "2006 09 28 13 38 45 07 00", format=0x5555557c91d6 "%4d%2d%2d%2d%2d%2d") at isoc99_sscanf.c:31
#2  0x0000555555636394 in metadata_date_time_construct_from_exif ()
#3  0x000055555571fb6a in photo_metadata_get_date_time ()
#4  0x000055555571fcc8 in photo_metadata_get_first_date_time ()
#5  0x000055555565198f in photo_prepare_for_import ()
#6  0x00005555555ecdef in ??? ()
#7  0x0000555555750898 in ??? ()
#8  0x00007ffff7ef28c2 in g_thread_pool_thread_proxy (data=<optimized out>)
    at ../glib/gthreadpool.c:336
#9  0x00007ffff7ef1d29 in g_thread_proxy (data=0x7fffec0036d0)
    at ../glib/gthread.c:835
#10 0x00007ffff66abea9 in start_thread (arg=<optimized out>)
    at pthread_create.c:444
#11 0x00007ffff6733a44 in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:100
(gdb) 
```

**Comment by jeremypw** [comment]
At first glance it looks like the issue already fixed (hopefully) with #785.  Not released yet though.
